In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sber_data = pd.read_csv('data/sber_data.csv')
sber_data.head()

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_quota,school_education_centers_raion,school_education_centers_top_20_raion,...,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,mosque_count_1000,price_doc
0,1,43,27.0,4.0,Bibirevo,5001.0,5,11065.0,5,0,...,0.637189,0.947962,0.177975,0.625783,0.628187,14.053047,7.389498,good,0,5850000
1,2,34,19.0,3.0,Nagatinskij Zaton,3119.0,5,6237.0,8,0,...,0.688796,1.072315,0.273345,0.967821,0.471447,6.829889,0.709260,excellent,0,6000000
2,3,43,29.0,2.0,Tekstil'shhiki,1463.0,4,5580.0,7,0,...,1.543049,0.391957,0.158072,3.178751,0.755946,4.273200,3.156423,poor,0,5700000
3,4,89,50.0,9.0,Mitino,6839.0,9,17063.0,10,0,...,0.934273,0.892674,0.236455,1.031777,1.561505,16.990677,16.041521,good,0,13100000
4,5,77,77.0,4.0,Basmannoe,3240.0,7,7770.0,9,0,...,0.077901,0.810801,0.376838,0.378756,0.121681,1.112486,1.800125,excellent,0,16331452

In [3]:
display(sber_data.tail())

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_quota,school_education_centers_raion,school_education_centers_top_20_raion,...,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,mosque_count_1000,price_doc
30466,30469,44,27.0,7.0,Otradnoe,5088.0,4,12721.0,4,0,...,1.103579,0.167718,0.349899,1.235066,0.612359,7.482165,4.836787,good,0,7400000
30467,30470,86,59.0,3.0,Tverskoe,1874.0,4,6772.0,4,1,...,0.069986,0.086552,0.362681,0.850385,0.310021,0.778428,1.450108,poor,0,25000000
30468,30471,45,NaN,10.0,Poselenie Vnukovskoe,NaN,0,NaN,0,0,...,4.338453,1.339078,1.234235,1.192543,1.186621,13.459593,9.890758,no data,0,6970959
30469,30472,64,32.0,5.0,Obruchevskoe,2372.0,6,6083.0,8,0,...,1.204798,1.340017,0.130667,1.644053,0.476021,2.088193,4.119706,satisfactory,0,13500000
30470,30473,43,28.0,1.0,Novogireevo,2215.0,4,5824.0,4,0,...,2.108265,0.825811,0.378950,0.480531,0.867332,0.688707,0.127867,poor,0,5600000

In [20]:
sber_data['sub_area'].value_counts().to_frame()

                                sub_area
Poselenie Sosenskoe                 1776
Nekrasovka                          1611
Poselenie Vnukovskoe                1372
Poselenie Moskovskij                 925
Poselenie Voskresenskoe              713
...                                  ...
Molzhaninovskoe                        3
Poselenie Shhapovskoe                  2
Poselenie Kievskij                     2
Poselenie Klenovskoe                   1
Poselenie Mihajlovo-Jarcevskoe         1

[146 rows x 1 columns]

In [22]:
sber_data.sort_values('price_doc')

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_quota,school_education_centers_raion,school_education_centers_top_20_raion,...,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,mosque_count_1000,price_doc
20244,20247,72,37.0,11.0,Gol'janovo,5041.0,6,11081.0,7,0,...,1.695963,0.804250,0.889795,1.157382,1.162542,12.207245,8.738948,good,0,100000
1167,1168,38,23.0,9.0,Beskudnikovskoe,2757.0,5,7327.0,5,0,...,0.621834,0.612635,0.347734,1.275573,1.273114,9.947039,7.224543,poor,0,190000
1169,1170,47,31.0,7.0,Savelki,1065.0,3,4674.0,3,0,...,0.933860,5.490137,0.378393,1.050189,1.053570,1.899959,3.735541,no data,0,200000
9221,9224,40,25.0,1.0,Novo-Peredelkino,4249.0,7,9373.0,7,0,...,2.739591,0.745126,0.745409,1.034987,0.927385,11.890448,7.737708,good,0,260000
3258,3261,31,19.0,5.0,Caricyno,3390.0,4,5631.0,5,0,...,1.351512,0.220301,0.300484,2.342586,0.590917,8.111188,2.260325,poor,0,300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6319,6322,206,128.0,2.0,Pokrovskoe Streshnevo,922.0,2,3577.0,4,0,...,0.814473,0.847085,0.741939,2.522564,0.893692,10.996972,9.566927,poor,0,78802248
19095,19098,184,85.0,10.0,Ramenki,903.0,8,7788.0,8,0,...,0.413282,0.451470,0.883583,0.980110,0.984219,5.046995,2.600478,satisfactory,0,80777440
7457,7460,185,66.0,33.0,Ramenki,903.0,8,7788.0,8,0,...,0.413282,0.451470,0.883583,0.980110,0.984219,5.046995,2.600478,satisfactory,0,91066096
28326,28329,220,144.0,3.0,Presnenskoe,3240.0,7,10602.0,9,0,...,0.185520,0.742409,0.345084,0.226752,0.140002,0.736765,0.722784,excellent,0,95122496
2118,2121,55,31.0,12.0,Teplyj Stan,4523.0,5,9443.0,6,0,...,1.239758,1.284828,0.432346,1.350731,0.665990,2.262960,3.781790,good,0,111111112